CREATE PROCEDURE log_photo_view (parm_user_id INT, parm_photo_id INT, parm_site_id INT)
BEGIN

DECLARE last_seen datetime;
SELECT updated_dt INTO last_seen FROM photo_view 
    WHERE photo_id=parm_photo_id 
    AND user_id=parm_user_id
    AND site_id=parm_site_id;

REPLACE INTO photo_view (photo_id, user_id, site_id) 
    VALUES (parm_photo_id, parm_user_id, parm_site_id);
SELECT last_seen;

END

-- DROP PROCEDURE log_photo_view
-- CALL log_photo_view (1, 4697, 1)